### ISSUE TITLE
生成失败了

### ISSUE THREAD

**Issue by Jony1943** [xiyun-international/vue-route-webpack-plugin#1]
一直没有成功，报这个错
![image](https://user-images.githubusercontent.com/19758010/63324709-2fa08500-c35b-11e9-92ec-b5349b2a989f.png)

**Comment by kybetter** [comment]
收到，正在排查问题，能提供下你插件的配置项和路由的配置吗？

**Comment by kybetter** [comment]
已发布 1.1.4 修复自定义配置时的固定目录问题和 windows 兼容问题。
如果还有问题欢迎继续提 issue。

**Comment by Jony1943** [comment]
有些疑问：
1、首先对于这个插件，我理解的是，主路由文件还是得自己写，这个插件只是帮助生成子路由文件，对不对呢？
2、不知道我的写法对不对，比如子文件的路径，主路由文件里面的引入子路由的方式，`component`是一个`frame.vue`，里面就一个`route-view`标签
3、生成的`children.js`，引入的组件（其实是个页面）地址不对，少了文件夹名字`“model”`，这个`“\”`也不对，应该是`“/”`
4、生成的`path`好像也不对，子路由在主路由的`path: '/model'`下，`children.js`里面应该是`path: 'selected'`
[下面是我的练习项目截图]
![image](https://user-images.githubusercontent.com/19758010/63346950-ad2eba00-c388-11e9-95e6-ff73eedb073a.png)

**Comment by kybetter** [comment]
多谢反馈。
关于第一点，我们会优化插件的说明文档，以便能更清晰地传达出来插件的主要用途。

第二点，我建议 frame.vue 还是放在 views 目录下，因为它是路由的主入口文件，建议放在 views/layout/ 这样的目录结构里面。

第三点和第四点是插件对 windows 的兼容性问题，会尽快修复。

**Comment by Jony1943** [comment]
哈哈，等了十几个小时没有回复，刚把后续问题删除了另外新建了一个issue，你就回复了
![image](https://user-images.githubusercontent.com/19758010/63397602-a8f0b400-c3fd-11e9-8754-17b05e35c7b5.png)
