### ISSUE TITLE
生成的children.js有些问题

### ISSUE THREAD

**Issue by Jony1943** [xiyun-international/vue-route-webpack-plugin#2]
有些疑问：
1、首先对于这个插件，我理解的是，主路由文件还是得自己写，这个插件只是帮助生成子路由文件，对不对呢？
2、不知道我的写法对不对，比如子文件的路径，主路由文件里面的引入子路由的方式，component是一个frame.vue，里面就一个route-view标签
3、生成的children.js，引入的组件（其实是个页面）地址不对，少了文件夹名字“model”，这个“\”也不对，应该是“/”
4、生成的path好像也不对，子路由在主路由的path: '/model'下，children.js里面应该是path: 'selected'
[下面是我的练习项目截图]
![image](https://user-images.githubusercontent.com/19758010/63397042-d76d8f80-c3fb-11e9-86b2-3c4eaab7a48f.png)

**Comment by kybetter** [comment]
发布了新版，你更新下版本看看还会不会出现 3、4 这两个问题的

**Comment by Jony1943** [comment]
还是有些问题：
1、这个斜线，要左斜线
2、path
![image](https://user-images.githubusercontent.com/19758010/63402727-135e2000-c40f-11e9-8372-ca54c6e267d6.png)

**Comment by kybetter** [comment]
发布了新版，经过测试在 windows 本上能正常展示分隔符了，你更新版本看下的。多谢反馈这些宝贵的问题。

**Comment by Jony1943** [comment]
帮我看下我整个路由的写法对不对（引用和嵌套），这个生成的children.js里面，`path`有问题，`path:‘model/selected’`改成`path:'selected'`，页面才能显示出来：
![image](https://user-images.githubusercontent.com/19758010/63410399-cf2a4a00-c425-11e9-9dba-bfe08af32903.png)

**Comment by kybetter** [comment]
因为你的子页面已经在 model 下了，路由配置那多了个 model，去掉 model 就可以了：
```js
// @route('/selected')
```

**Comment by Jony1943** [comment]
赞
![image](https://user-images.githubusercontent.com/19758010/63411421-16b1d580-c428-11e9-9e07-d44013e39693.png)
 问题解决了。
我还是有点迷惑，上面说的第1点，这个插件只是用来生成子路由文件的？麻烦之后能在`README.md`详细介绍一下

**Comment by kybetter** [comment]
好的，后续会更新文档说明。
