### ISSUE TITLE
提一个想法

### ISSUE THREAD

**Issue by rxxy** [xiyun-international/vue-route-webpack-plugin#5]
我自己的想法，可以讨论哈

可不可以和`nuxt.js`一样，只要按照一定规范来组织页面文件，就可以自动生成路由呢?

达到可以`不配置`、`简单配置`、`全部配置`，三种方式都可以生成路由，这样保证了灵活性的同时又能达到`约定大于配置`的目标、在按照约定编写代码时配置项最少。

**Comment by rxxy** [comment]
也可以做几种扫描策略

**Comment by rxxy** [comment]
也可以做几种扫描策略

对于view(可自定义)文件夹下:

1. 所有vue文件都生成路由
2. 正则指定要作为路由的vue文件
3. 正则指定不作为路由的vue文件

**Comment by kybetter** [comment]
首先感谢你的建议。

其实我们很早就实践过相似的框架了，比如：[UmiJS](https://umijs.org/zh/guide/router.html#%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1)。

可以看到它使用的就是像你说的基于约定的路由机制。

稍微浏览一下动态路由这部分的内容你会发现，如果要使用基于约定式的路由，那么就要接受：`$post` 这样的目录名和 `$id$.js` 这样的文件名，因为只有根据约定好的文件名才能生成出指定的路由。

而这样的约定和表意不明的文件名是很多人都不希望看到的，使用`UserDetail.vue`这样表意清楚的文件名更能彰显出这个文件是做什么用的，这是其一。

其二、咱们开发的组件，有两种区别，一种是这个组件就是用来承载页面用的页面级组件，另一种是功能和逻辑型组件。通常路由所指的就是这些页面级组件，比如：`UserList.vue`，`UserDetail.vue`，或者，如果是在`user` 文件夹下面那么文件名可能就是`List.vue`、`Detail.vue`，你想要取什么样的文件名都随你。

但是如果一旦要加上规定，处于某种结构下的文件才会作为路由文件去扫描，那么上述例子就可能就会变成这样：
```
user/
    list/
      index.vue
    detail/
      index.vue    
```
这种文件结构是大家都希望看到的吗？有可能有的人就是喜欢这种结构，有的人却又喜欢另外一种结构，会出现众口难调的局面。

现在来看一下Java 中大名鼎鼎的 SpringBoot 框架是如何处理路由的：
```java
@Controller
@ResponseBody
@RequestMapping(value = "/index")
public class IndexController {

    @RequestMapping(value = "/login")
    public String login()
    {
        return "我是登录页";
    }
}
```
其中的 login 方法就相当于前端的 login 页面，要为 login 方法分配什么样的访问路由完全取决于你，这个例子就很规矩地分配了 "/login" 路由给它使用。这也是我们最后决定借鉴 SpringBoot 配置路由的方式来做路由配置的原因。

**Comment by rxxy** [comment]
嗯，我想过这几种情况了，我的意思是约定和配置共存，不希望使用约定那就使用配置覆盖他就好了，文件名还是可以随意起，`约定优于配置，配置覆盖约定`。这样一来还是非常灵活的。

1. 对于`$id$.js` 或 `$post` 这种不太能接受的文件名完全可以由自己来决定取舍，取这样的文件名或在vue文件自己配置
2. 对于`UserDetail.vue`这种不想作为路由的组件可以使用一定的正则排除，或者在`UserDetail.vue`中使用配置项(类似`isRoute: false`)排除

我看到这个库的路由配置是使用注释的方式，我觉得有些不严谨，我在想能不能把配置放到大括号内部，和`name,data,mounted`这些参数平级，并使用`vue-loader`解析。

**Comment by kybetter** [comment]
看一下对比你应该能知道接下来我们要做什么了：
```js
// @route('/user/list')
export default {}
```
vs

```js
@route('/user/list')
export default {}
```

vue 3.0 已经在路上了。^_^

**Comment by wubaiqing** [comment]
这是产品定位问题，我到是觉得可以作为`企业级脚手架`的补充。

如果你的团队遵循约定大于配置，优先选择企业级脚手架，因为它们是标准化的，业界也承认它们的存在，技术上也更加的成熟。内部也没有推广成本。

所以我们没必要克隆一遍已有的产物；因为它们做的就很好，比我们更专业。
这类的脚手架有：[UmiJS](https://umijs.org/)、[NuxtJS](https://nuxtjs.org/)、[NextJS](https://nextjs.org/)。

我们应该想的是：
基于 `企业级的脚手架` 基础上，提供一个使用 “注解声明路由” 的解决方案，如，提供插件的方式。实现和企业级的脚手架 **共存**；

两套方案共存，优先级是：
1. 企业级脚手架的规则优先；或让用户选择谁更优先；
2. 我们作为另一种实现方式，`弥补欠缺`而存在；

等到社区成熟或认为这套方案可行；他们在自有的系统上支持，能随时替换掉我们。

**Comment by rxxy** [comment]
> 看一下对比你应该能知道接下来我们要做什么了：
> 
> ```js
> // @route('/user/list')
> export default {}
> ```
> 
> vs
> 
> ```js
> @route('/user/list')
> export default {}
> ```
> 
> vue 3.0 已经在路上了。^_^

如果是这样的话那就非常优雅了，这种应该是最好的写法。

**Comment by rxxy** [comment]
> 这是产品定位问题，我到是觉得可以作为`企业级脚手架`的补充。
> 
> 如果你的团队遵循约定大于配置，优先选择企业级脚手架，因为它们是标准化的，业界也承认它们的存在，技术上也更加的成熟。内部也没有推广成本。
> 
> 所以我们没必要克隆一遍已有的产物；因为它们做的就很好，比我们更专业。
> 这类的脚手架有：[UmiJS](https://umijs.org/)、[NuxtJS](https://nuxtjs.org/)、[NextJS](https://nextjs.org/)。
> 
> 我们应该想的是：
> 基于 `企业级的脚手架` 基础上，提供一个使用 “注解声明路由” 的解决方案，如，提供插件的方式。实现和企业级的脚手架 **共存**；
> 
> 两套方案共存，优先级是：
> 
> 1. 企业级脚手架的规则优先；或让用户选择谁更优先；
> 2. 我们作为另一种实现方式，`弥补欠缺`而存在；
> 
> 等到社区成熟或认为这套方案可行；他们在自有的系统上支持，能随时替换掉我们。

确实，企业级脚手架也提供了差不多的功能了，但是有一些切换成本。小的需求先自己搞一个嘿嘿
